config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :productos
  root 'welcome#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/producto.rb
class Producto < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
    def show
        @producto = Producto.find(params[:id])
    end

    def index
        @productos = Producto.all
    end

    def new
    end

    def create
        @producto = Producto.new(params.require(:producto).permit(:nombre, :nombre_bonito, :descripcion, :precio, :activo))
 
        @producto.save
        redirect_to @producto
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <span class="copyright">Copyright &copy; JukiMods 2019</span>
      </div>
      <div class="col-md-4">
        <ul class="list-inline social-buttons">
          <li class="list-inline-item">
            <a href="https://twitter.com/jukimods" target="_blank">
              <i class="fa fa-twitter"></i>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="https://www.instagram.com/jukimods/" target="_blank">
              <i class="fa fa-instagram"></i>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="https://www.youtube.com/channel/UCEK_4Ec06vy2UStChKMq4fg" target="_blank">
              <i class="fa fa-youtube"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
  <div class="container">
  <%= link_to image_tag("logo/JUKI_logo.svg"), ".", class: "navbar-brand js-scroll-trigger" %>  
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fa fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#productos">Productos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#records">Records</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#equipo">Equipo</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#" data-toggle="modal" data-target="#ContactaModal">Escríbenos</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JukiOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <%= javascript_include_tag 'https://www.googletagmanager.com/gtag/js?id=UA-109098764-1' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>
      <%= yield %>
  </body>
</html>

app/views/layouts/index.html.erb
<%= render "layouts/header" %>
<h1>JukiMods</h1>    
<%= render "layouts/footer" %>

app/views/productos/index.html.erb
<%= render "layouts/header" %>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<div class="container">
    <h1> Catálogo JukiMods </h1>
    
    <% @productos.each do |producto| %>
        <% if producto.activo %>
            <h1>Juki <%= producto.nombre %></h1>
            <p>
            <%= producto.descripcion %>
            </p>
            
            <p>
            <strong>Precio: </strong>
            <%= producto.precio %>€
            </p>
        <% else %>
            <p> El <% @roducto.nombre %> no se encuentra a la venta ahora mismo.</p>
        <% end %>
    <% end %>
    <br><br>
    <%= link_to 'Añadir producto', new_producto_path %>
</div>
<%= render "layouts/footer" %>

app/views/productos/new.html.erb
<%= render "layouts/header" %>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<div class="container">
<h1>Productos</h1>
    <%= form_with scope: :producto, url: productos_path, local: true do |form| %>
        <p>
            <%= form.label :nombre %><br>
            <%= form.text_field :nombre %>
        </p>
    
        <p>
            <%= form.label :nombre_bonito %><br>
            <%= form.text_field :nombre_bonito %>
        </p>

        <p>
            <%= form.label :descripciom %><br>
            <%= form.text_area :descripcion %>
        </p>
    
        <p>
            <%= form.label :precio %><br>
            <%= form.number_field :precio %><br>
        </p>

        <p>
            <%= form.label :activo %><br>
            <%= form.check_box :activo %><br>
        </p>

        <p>
            <%= form.submit %>
        </p>
    <% end %>
    <%= link_to 'Volver al catálogo', productos_path %>
</div
<%= render "layouts/footer" %>

app/views/productos/show.html.erb
<%= render "layouts/header" %>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<div class="container">
    <% if @producto.activo %>
        <h1>Juki <%= @producto.nombre %></h1>
        <p>
        <%= @producto.descripcion %>
        </p>
        
        <p>
        <strong>Precio: </strong>
        <%= @producto.precio %>€
        </p>
    <% else %>
        <p> El <% @producto.nombre %> no se encuentra a la venta ahora mismo.</p>
    <% end %>
    <%= link_to 'Volver al catálogo', productos_path %>
</div
<%= render "layouts/footer" %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/welcome/index.html.erb
<%= render "layouts/header" %>
<!-- Header -->
<header class="masthead">
  <div class="container">
      <div class="row justify-content-md-center" >
          <div class="col-lg-8 text-center">
            <div class="intro-text">
              <div class="intro-lead-in">Bienvenidos a:</div>
              <div class="intro-heading">JukiMods</div>
              <%= link_to 'Catálogo', {controller: 'productos'}, class: "btn btn-xl js-scroll-trigger" %>
            </div>
          </div>
        </div>
      </div>
</header>
 <div class="container">
    <div class="row justify-content-md-center align-items-center" >
      <div class="col-lg-5 text-center">
        <h4 style="text-transform: none;">Los cubos fabricados por Juki Mods están especialmente diseñados para la competición de alto nivel.
Trabajo única y exclusivamente con los cubos top actuales y solo uso los mejores lubricantes del mercado.</h4>
      </div>
      <div class="col-lg-7 text-center">
        <a class="twitter-timeline" data-height="400" href="https://twitter.com/JukiMods?ref_src=twsrc%5Etfw">Tweets by JukiMods</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
      </div>
    </div>
</div>
<%= render "layouts/footer" %>